### PR TITLE
Enable `bytes` to build with no rust version limit.

### PR DESCRIPTION
**Pull request by daxpedda**
#17 is currently stuck because `bytes` doesn't support rust `1.20.0` anymore. This should alleviate the issue.

### CODE REVIEW

**Comment by carllerche** [comment]
Why don't we bump the minimum supported version to 1.39? Do you want to do that?

**Comment by daxpedda** [comment]
Completely up to you, I don't mind either way.
If you want I can make a PR to upgrade to rust edition 2018.

**Comment by carllerche** [comment]
I like it, lets use the breaking change to bump to 2018 and min version of 1.39

**Comment by daxpedda** [comment]
On it.

**Comment by daxpedda** [comment]
Closed in favor of #19.

**Pull request closed without merging**
